services:
    app:
        build:
            context: .
            args:
                - ENV=Development
        ports:
            - "80:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - CUSTOM_APPSETTINGS=Test
        env_file:
            -   .env.docker
        depends_on:
            - database
            - redis
            - smtp
    database:
        image: postgres:14
        environment:
            - POSTGRES_USER=testUser
            - POSTGRES_PASSWORD=testPassword
            - POSTGRES_DB=contest-app
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    smtp:
        image: rnwood/smtp4dev
        ports:
            - "5000:80"
            - "2525:25"
    redis:
        image: redis:7
        healthcheck:
            test: [ 'CMD', 'redis-cli', 'ping' ]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/var/lib/redis/data
volumes:
    postgres-data:
    redis-data:
