name: Pull request checks

concurrency:
    group: ${{ github.head_ref || github.ref_name }}
    cancel-in-progress: true

on:
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            - name: Setup .Net 8
              uses: actions/setup-dotnet@v4
              with:
                    dotnet-version: '8.x'
                    cache: true
                    cache-dependency-path: |
                        './src/Core/package.lock.json'
                        './src/Api/package.lock.json'
                        './src/Infrastructure/package.lock.json'
                        './tests/Core.Tests/package.lock.json'
                    
            - name: Install Dependencies
              run: dotnet restore --locked-mode
              
            - name: Build
              run: dotnet build
              
            - name: Run Stylecop Check
              run: dotnet format analyzers --verify-no-changes && dotnet format style --verify-no-changes

            - name: Run Csharpier Check
              run: dotnet csharpier . --check

            - name: Run Unit / Integration Tests
              run: dotnet test
